arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
output-class: AppLocalizations
untranslated-messages-file: lib/l10n/missing_translations.json
synthetic-package: false
nullable-getter: false
